swingerman/ha-dual-smart-thermostat

.devcontainer/configuration.yaml, .devcontainer/devcontainer.json, README.md, custom_components/dual_smart_thermostat/__init__.py, custom_components/dual_smart_thermostat/climate.py, custom_components/dual_smart_thermostat/const.py, tests/test_thermostat.py
- adds off, cool heat, heat_cool hvac modes
- remembers last hvac_mode after restart (only if initial_hvac_mode is not set)
- no platfrom setup error on startup
Fixes #8
Fixes #7
Fixes #5
=> fix: remembers heating mode

.devcontainer/configuration.yaml, .github/workflows/hacs-validate.yaml, .github/workflows/linting.yaml, .github/workflows/tests.yaml, custom_components/dual_smart_thermostat/climate.py, tests/test_thermostat.py
=> fix: switches hvac modes properly in dual mode

.devcontainer/configuration.yaml, custom_components/dual_smart_thermostat/climate.py, custom_components/dual_smart_thermostat/const.py, hacs.json, tests/test_thermostat.py
=> fix: correctly handles and communicates hvac modes

custom_components/dual_smart_thermostat/climate.py, custom_components/dual_smart_thermostat/const.py
Hi, 
Thanks for this great great integration! I made my own custom generic thermostat some time ago to add some presets that where supported by my thermostat but missing in the generic one. Here's a PR to add them as well to your integration if you will.
Cheers
=> Add eco, comfort, at home and anti-freeze presets

.gitignore, custom_components/dual_smart_thermostat/climate.py
I realized that I didn't add the new presets to the set_preset_mode method...
Here it is with some refactoring to make it shorter.
Tested at home.
=> fix set preset modes with new presets.

README.md
=> Update readme with new presets

custom_components/dual_smart_thermostat/climate.py
=> Fix inizialization after yaml reload

custom_components/dual_smart_thermostat/climate.py
This PR is to avoid issues caused by wrong configuration as issue #43
=> Do not allow cooler entity equal to heater entity

custom_components/dual_smart_thermostat/climate.py, tests/test_thermostat.py
Some minor fixes in `min_cycle_duration` controls
=> Minor fixes for "min_cycle_duration"

.vscode/settings.json, action/action.py, requirements.txt, tests/test_thermostat.py
=> test: Heat/Cool HVAC mode not available

.github/workflows/linting.yaml, .github/workflows/tests.yaml, custom_components/dual_smart_thermostat/climate.py, custom_components/dual_smart_thermostat/const.py, hacs.json, requirements.txt, tests/test_thermostat.py
enables the termostat to use the tolerancees both for heater and cooler when in heat_cool mode
Fixes #48
=> feat: "hot_tolerance" not woking as expected when in heat_cool mode

.github/workflows/hacs-validate.yaml, .github/workflows/linting.yaml, .github/workflows/quality-check.yaml, .github/workflows/tests.yaml, custom_components/dual_smart_thermostat/climate.py
=> Opening state unknown breaks is_opening_open logic

custom_components/dual_smart_thermostat/climate.py, custom_components/dual_smart_thermostat/const.py, custom_components/dual_smart_thermostat/opening_manager.py, custom_components/dual_smart_thermostat/services.yaml
=> Flatten deepley nested code

README.md
=> Add Example configurations

README.md, custom_components/dual_smart_thermostat/climate.py
Note that this is my first PR to an HA integration and I'm not really sure how to test this but the changes seem to make sense.
=> feat: adds support for preset_mode: sleep

custom_components/dual_smart_thermostat/climate.py, tests/test_thermostat.py
=> fix: heating is not stopping when i start cooling mode

custom_components/dual_smart_thermostat/climate.py, custom_components/dual_smart_thermostat/services.yaml, requirements-test.txt, tests/test_thermostat.py
=> fix: uses new enums instead of depricated ones

README.md, custom_components/dual_smart_thermostat/climate.py, custom_components/dual_smart_thermostat/const.py, tests/FEATURES.md, tests/test_heater_mode.py
=> feat(AUX heating): Adds option to keep primary heater on while aux heater is on

custom_components/dual_smart_thermostat/manifest.json, hacs.json
=> chore: updates required home assistatnt version

config/configuration.yaml, custom_components/dual_smart_thermostat/climate.py, tests/test_cooler_mode.py, tests/test_dual_mode.py, tests/test_heater_mode.py
Fixes #130
Fixes #121
Fixes #80
=> fix: hvac mode and temperature issues

custom_components/dual_smart_thermostat/climate.py, tests/test_cooler_mode.py, tests/test_dual_mode.py, tests/test_heater_mode.py
=> fix: restores support for climate.turn_on

README.md, tests/test_heater_mode.py
=> docs: add unique_id to documentation

custom_components/dual_smart_thermostat/manifest.json, requirements-dev.txt, requirements.txt, tests/test_cooler_mode.py, tests/test_dual_mode.py, tests/test_fan_mode.py, tests/test_heater_mode.py
=> chore: update home assistant version

config/configuration.yaml, custom_components/dual_smart_thermostat/climate.py, custom_components/dual_smart_thermostat/hvac_device/controllable_hvac_device.py, custom_components/dual_smart_thermostat/hvac_device/cooler_fan_device.py, custom_components/dual_smart_thermostat/hvac_device/heater_aux_heater_device.py, custom_components/dual_smart_thermostat/hvac_device/heater_cooler_device.py, custom_components/dual_smart_thermostat/hvac_device/specific_hvac_device.py, scripts/setup, tests/common.py, tests/test_cooler_mode.py, tests/test_dual_mode.py, tests/test_fan_mode.py, tests/test_heater_mode.py
=> feat: restores previous hvac mode on toggle

config/configuration.yaml, custom_components/dual_smart_thermostat/climate.py, custom_components/dual_smart_thermostat/hvac_device/cooler_device.py, custom_components/dual_smart_thermostat/hvac_device/cooler_fan_device.py, custom_components/dual_smart_thermostat/hvac_device/heater_aux_heater_device.py, custom_components/dual_smart_thermostat/hvac_device/heater_device.py, custom_components/dual_smart_thermostat/hvac_device/hvac_device.py, custom_components/dual_smart_thermostat/hvac_device/hvac_device_factory.py, custom_components/dual_smart_thermostat/hvac_device/specific_hvac_device.py, custom_components/dual_smart_thermostat/managers/feature_manager.py, custom_components/dual_smart_thermostat/managers/temperature_manager.py, tests/__init__.py, tests/test_dual_mode.py
=> fix: the heat/cool fuction is not working with the fan-mode

README.md, config/configuration.yaml, custom_components/dual_smart_thermostat/hvac_action_reason/hvac_action_reason_internal.py, custom_components/dual_smart_thermostat/hvac_device/cooler_fan_device.py, custom_components/dual_smart_thermostat/managers/feature_manager.py, tests/__init__.py, tests/test_dual_mode.py
=> fix: unable to set hvac mode after selecting preset

custom_components/dual_smart_thermostat/climate.py, custom_components/dual_smart_thermostat/const.py, custom_components/dual_smart_thermostat/hvac_action_reason/hvac_action_reason.py, custom_components/dual_smart_thermostat/hvac_action_reason/hvac_action_reason_external.py, custom_components/dual_smart_thermostat/hvac_action_reason/hvac_action_reason_internal.py, custom_components/dual_smart_thermostat/managers/opening_manager.py
=> fix: EventType and StrEnum  was deprecated

custom_components/dual_smart_thermostat/managers/temperature_manager.py, tests/test_dual_mode.py, tests/test_fan_mode.py
=> fix: fan hot tolerance issue

config/configuration.yaml, custom_components/dual_smart_thermostat/hvac_device/heater_cooler_device.py, tests/test_dual_mode.py
=> fix: only turns off heater when on if overheated

custom_components/dual_smart_thermostat/managers/preset_manager.py, tests/test_dual_mode.py
=> fix: preset reselection should reset environment targets

README.md, config/configuration.yaml, custom_components/dual_smart_thermostat/climate.py, custom_components/dual_smart_thermostat/managers/environment_manager.py, custom_components/dual_smart_thermostat/managers/feature_manager.py, custom_components/dual_smart_thermostat/managers/preset_manager.py, tests/__init__.py, tests/test_dual_mode.py
=> feat: picks target temperature from preset range if target temp is not set

custom_components/dual_smart_thermostat/climate.py, custom_components/dual_smart_thermostat/hvac_device/heater_cooler_device.py, hacs.json, requirements-dev.txt, requirements.txt, tests/common.py, tests/test_cooler_mode.py, tests/test_dual_mode.py, tests/test_fan_mode.py
=> fix: component won't run on Core v2024.3.1 - config warns about exception

custom_components/dual_smart_thermostat/hvac_device/fan_device.py, tests/test_fan_mode.py
=> fix: hvac_action set to fan when active

custom_components/dual_smart_thermostat/managers/hvac_power_manager.py
=> fix: rounds percentage

custom_components/dual_smart_thermostat/climate.py, custom_components/dual_smart_thermostat/managers/hvac_power_manager.py
=> sets hvac_power_level to when off and ensures the values are rounded

custom_components/dual_smart_thermostat/climate.py, custom_components/dual_smart_thermostat/hvac_controller/generic_controller.py, custom_components/dual_smart_thermostat/hvac_device/generic_hvac_device.py, custom_components/dual_smart_thermostat/managers/environment_manager.py, custom_components/dual_smart_thermostat/managers/hvac_power_manager.py, custom_components/dual_smart_thermostat/managers/opening_manager.py, tests/test_cooler_mode.py
=> fix: sets proper power levels if device state changes

custom_components/dual_smart_thermostat/managers/hvac_power_manager.py, tests/test_cooler_mode.py
=> fix: rounds percentage proper

config/configuration.yaml, custom_components/dual_smart_thermostat/hvac_device/heat_pump_device.py, tests/test_heat_pump_mode.py
=> fix: sets missing hvac action for heat pump device

custom_components/dual_smart_thermostat/managers/environment_manager.py, tests/__init__.py, tests/test_dual_mode.py
=> fix: don't send target temp range form old state if heat cool mode is off

custom_components/dual_smart_thermostat/climate.py, custom_components/dual_smart_thermostat/hvac_controller/heater_controller.py, custom_components/dual_smart_thermostat/managers/environment_manager.py
=> fix: oly applies max_floor_temp old state if not set from config

custom_components/dual_smart_thermostat/climate.py
=> feat : log message for stall recovery

custom_components/dual_smart_thermostat/hvac_action_reason/hvac_action_reason_internal.py, custom_components/dual_smart_thermostat/hvac_controller/generic_controller.py, custom_components/dual_smart_thermostat/hvac_device/cooler_fan_device.py, custom_components/dual_smart_thermostat/hvac_device/generic_hvac_device.py, tests/__init__.py, tests/common.py, tests/test_fan_mode.py
=> fix: respects min_cycle_duration while switching to fan

.devcontainer.json, .github/workflows/linting.yaml, .github/workflows/tests.yaml, .pre-commit-config.yaml, custom_components/dual_smart_thermostat/managers/feature_manager.py, requirements-dev.txt, setup.cfg, tests/common.py, tests/test_dual_mode.py, tests/test_fan_mode.py, tests/test_heat_pump_mode.py
=> fix: ensures supported features is never zero

custom_components/dual_smart_thermostat/climate.py, tests/test_cooler_mode.py, tests/test_dual_mode.py, tests/test_heater_mode.py
=> fix: logs warning if senosr recovers

custom_components/dual_smart_thermostat/climate.py, tests/test_cooler_mode.py, tests/test_dry_mode.py, tests/test_fan_mode.py, tests/test_heater_mode.py
=> feat - avoids controlling hvac when themrostat is off

config/configuration.yaml, custom_components/dual_smart_thermostat/managers/preset_manager.py, custom_components/dual_smart_thermostat/manifest.json
=> fix: thermostat turn off after restart HA in some conditions

custom_components/dual_smart_thermostat/climate.py, tests/test_fan_mode.py
=> fix: avoids controlling hvac while off

custom_components/dual_smart_thermostat/climate.py, tests/test_cooler_mode.py, tests/test_heater_mode.py
=> feat: enables to set `hvac_mode` with temperature from automation

README.md, custom_components/dual_smart_thermostat/climate.py, custom_components/dual_smart_thermostat/managers/environment_manager.py, custom_components/dual_smart_thermostat/preset_env/preset_env.py, tests/__init__.py, tests/test_heater_mode.py
=> feat: adjustable minimum floor temperature with presets

config/configuration.yaml, custom_components/dual_smart_thermostat/managers/opening_manager.py, tests/test_cooler_mode.py, tests/test_dry_mode.py, tests/test_dual_mode.py, tests/test_fan_mode.py, tests/test_heater_mode.py
=> fix: Opening Timeout not working

custom_components/dual_smart_thermostat/climate.py, custom_components/dual_smart_thermostat/hvac_controller/heater_controller.py, custom_components/dual_smart_thermostat/hvac_controller/hvac_controller.py, custom_components/dual_smart_thermostat/hvac_device/generic_hvac_device.py, custom_components/dual_smart_thermostat/hvac_device/heater_device.py, custom_components/dual_smart_thermostat/managers/environment_manager.py, tests/test_heater_mode.py
=> feat: Trigger control if switch becomes available

custom_components/dual_smart_thermostat/climate.py, tests/test_fan_mode.py
=> feat: - Trigger control if switch becomes available

config/configuration.yaml, custom_components/dual_smart_thermostat/managers/environment_manager.py, custom_components/dual_smart_thermostat/managers/preset_manager.py, tests/test_dual_mode.py
=> [feat] - save last state in off state, so toggling after restart picks up last settings

custom_components/dual_smart_thermostat/climate.py, custom_components/dual_smart_thermostat/managers/environment_manager.py, tests/test_cooler_mode.py, tests/test_dual_mode.py, tests/test_heater_mode.py
=> feat: resets temperature/range back to the current presets settings

custom_components/dual_smart_thermostat/manifest.json
=> waits for binary_sensor before init component

README.md
Minor change on readme on opening instructions
=> Update the opening configuration variables section in  readme file
